services:


  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode
    environment:
      - CLUSTER_NAME=demo
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - namenode:/hadoop/dfs/name
      - ./spark-apps:/opt/spark-apps    
    ports:
      - "9000:9000"
      - "9870:9870"
    networks:
      - hadoop

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    hostname: datanode
    environment:
      - CLUSTER_NAME=demo
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - CORE_CONF_hadoop_http_staticuser_user=root
      - HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check=false
    volumes:
      - datanode:/hadoop/dfs/data
    ports:
      - "9864:9864"
    networks:
      - hadoop
    depends_on:
      - namenode


  spark-master:
    image: bde2020/spark-master:latest
    container_name: spark-master
    hostname: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_PORT=7077
      - SPARK_DRIVER_MEMORY=6g
      - SPARK_EXECUTOR_MEMORY=6g
      - SPARK_DRIVER_MAXRESULTSIZE=4g
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - hadoop


  spark-worker:
    image: bde2020/spark-worker:latest
    container_name: spark-worker
    hostname: spark-worker
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=6g
      - SPARK_WORKER_CORES=2
      - SPARK_EXECUTOR_MEMORY=6g
    networks:
      - hadoop
    depends_on:
      - spark-master

  spark-submit:
    image: bde2020/spark-submit:latest
    container_name: spark-submit
    hostname: spark-submit
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_DRIVER_MEMORY=6g
      - SPARK_EXECUTOR_MEMORY=6g
      - SPARK_DRIVER_MAXRESULTSIZE=4g
      - SPARK_LOCAL_DIRS=/tmp
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./spark-apps:/opt/spark-apps     
    networks:
      - hadoop
    depends_on:
      - spark-master
      - spark-worker


volumes:
  namenode:
  datanode:

networks:
  hadoop:
