version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: BDII_PROYII
      MYSQL_DATABASE: metrics
      MYSQL_USER: BDII_PROYII
      MYSQL_PASSWORD: BDII_PROYII
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./MySql_Init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  mysql-data: